name: bewell
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  flutter_screenutil: ^5.9.0
  logger: 
  get_storage: ^2.1.1
  injectable: ^2.3.2
  flutter_svg: ^2.0.10+1


dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  stacked_generator: ^1.3.3
  

flutter:
  uses-material-design: true


assets:
    - assets/icons/navbar/

